// <auto-generated />
using System;
using FreeLancerWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreeLancerWebApp.Migrations
{
    [DbContext(typeof(FreeLancerDbContext))]
    partial class FreeLancerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FreeLancerWebApp.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerCatID")
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("customer_email");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_name");

                    b.HasKey("ID");

                    b.HasIndex("CustomerCatID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[customer_name] IS NOT NULL");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.CustomerCat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cat_id")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cat_description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cat_name");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[cat_name] IS NOT NULL");

                    b.ToTable("customer_cats");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerID")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_description");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2")
                        .HasColumnName("job_end");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2")
                        .HasColumnName("job_start");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("job_state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("job_title");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.Quote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quote_id")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("quote_amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("quote_date");

                    b.Property<int>("FinalAmount")
                        .HasColumnType("int")
                        .HasColumnName("quote_final_amount");

                    b.Property<DateTime>("FinalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("quote_final_date");

                    b.Property<int>("JobID")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("quote_state");

                    b.HasKey("ID");

                    b.HasIndex("JobID");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.Customer", b =>
                {
                    b.HasOne("FreeLancerWebApp.Models.CustomerCat", "CustomerCat")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerCatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerCat");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.Job", b =>
                {
                    b.HasOne("FreeLancerWebApp.Models.Customer", "Customer")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.Quote", b =>
                {
                    b.HasOne("FreeLancerWebApp.Models.Job", "Job")
                        .WithMany("Quotes")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.Customer", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.CustomerCat", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("FreeLancerWebApp.Models.Job", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
